#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=10
start_service() {
 procd_open_instance
 procd_set_param command /usr/sbin/tr3600-fan-guard --boot
 procd_set_param respawn 3600 2 5
 procd_close_instance
}
